import './vds-aspect-ratio';
import './vds-gesture';
import './vds-poster';
// Buttons
import './vds-toggle-button';
import './vds-mute-button';
import './vds-play-button';
import './vds-fullscreen-button';
// Sliders
import './vds-slider';
import './vds-time-slider';
import './vds-volume-slider';
import './vds-slider-video';
import './vds-slider-value-text';
// Time
import './vds-time';
