<MediaPlayer>
  <MediaOutlet>
    <track
      src="/media/subs/english.vtt"
      kind="subtitles"
      label="English"
      srclang="en-US"
      default
      data-type="vtt"
    />
  </MediaOutlet>
</MediaPlayer>;
