import '../providers/video/vds-video';
import '../providers/hls/vds-hls';
import '../core/media/ui/vds-media-ui';
import '../core/media/controller/vds-media-controller';
import '../core/media/container/vds-media-container';
import '../ui/controls/slider/vds-slider';
import '../ui/controls/button/vds-button';
import '../ui/controls/toggle/vds-toggle';
import '../ui/controls/toggle-button/vds-toggle-button';
import '../ui/controls/play-button/vds-play-button';
import '../ui/controls/mute-button/vds-mute-button';
import '../ui/controls/fullscreen-button/vds-fullscreen-button';
import '../ui/controls/scrubber/vds-scrubber';
import '../ui/time/time/vds-time';
import '../ui/time/time-current/vds-time-current';
import '../ui/time/time-duration/vds-time-duration';
import '../ui/time/time-progress/vds-time-progress';
import '../ui/buffering-indicator/vds-buffering-indicator';

export * from './index';
