import type { InferComponentEvents } from 'maverick.js';
import type { ReactEventCallbacks } from 'maverick.js/react';

import type { MediaPlayerInstance } from './primitives/instances';

type PlayerCallbacks = keyof ReactEventCallbacks<InferComponentEvents<MediaPlayerInstance>>;

export const playerCallbacks: PlayerCallbacks[] = [
  'onAbort',
  'onAudioTrackChange',
  'onAudioTracksChange',
  'onAutoPlay',
  'onAutoPlayChange',
  'onAutoPlayFail',
  'onCanLoad',
  'onCanPlay',
  'onCanPlayThrough',
  'onControlsChange',
  'onDestroy',
  'onDurationChange',
  'onEmptied',
  'onEnd',
  'onEnded',
  'onError',
  'onFindMediaPlayer',
  'onFullscreenChange',
  'onFullscreenError',
  'onLiveChange',
  'onLiveEdgeChange',
  'onLoadedData',
  'onLoadedMetadata',
  'onLoadStart',
  'onLoopChange',
  'onOrientationChange',
  'onPause',
  'onPictureInPictureChange',
  'onPictureInPictureError',
  'onPlay',
  'onPlayFail',
  'onPlaying',
  'onPlaysInlineChange',
  'onPosterChange',
  'onProgress',
  'onProviderChange',
  'onProviderLoaderChange',
  'onProviderSetup',
  'onQualitiesChange',
  'onQualityChange',
  'onRateChange',
  'onReplay',
  'onSeeked',
  'onSeeking',
  'onSourceChange',
  'onSourceChange',
  'onStalled',
  'onStarted',
  'onStreamTypeChange',
  'onSuspend',
  'onTextTrackChange',
  'onTextTracksChange',
  'onTimeUpdate',
  'onTitleChange',
  'onVdsLog',
  'onVideoPresentationChange',
  'onVolumeChange',
  'onWaiting',
];
