import './vds-aspect-ratio';
import './vds-fullscreen-button';
import './vds-mute-button';
import './vds-play-button';
import './vds-slider';
import './vds-time-slider';
import './vds-time';
import './vds-toggle-button';
import './vds-volume-slider';
