sequenceDiagram
    alt Provider Update
        rect rgb(0, 255, 0, .1)
        Provider ->> Engine: Listen to `play` event
        Engine -->> Provider: Fires `play` event
        Provider ->> Context: Update
        Context -->> UI: `ContextUpdate`
        UI ->> UI: Trigger `render()`
        end
    else UI Update
        rect rgba(0, 0, 255, .1)
        Provider ->> Engine: Listen to `play` event
        Provider ->> Provider: Listen for `UserPlayEvent` event
        UI -->> Provider: Fires `UserPlayEvent`
        Provider ->> Engine: setPaused(false)
        Engine -->> Provider: Fires `play` event
        Provider ->> Context: Update
        Context -->> UI: `ContextUpdate`
        UI ->> UI: Trigger `render()`
        end
    end