classDiagram

class YouTubeProvider
class VimeoProvider
class DailymotionProvider
class Embed

YouTubeProvider -- Embed: uses
VimeoProvider -- Embed: uses
DailymotionProvider -- Embed: uses

class MediaEmbedProvider~ParamsType,MessageType~ {
    <<abstract>>
    getOrigin()* string
    buildParams()* ParamsType
    getDecoder()* Decoder
    getPreconnections()*
}

MediaEmbedProvider <|-- YouTubeProvider: extends
MediaEmbedProvider <|-- VimeoProvider: extends
MediaEmbedProvider <|-- DailymotionProvider: extends

class VideoProvider~EngineType = HTMLVideoElement~
class AudioProvider~EngineType = HTMLAudioElement~
class HlsProvider~EngineType = Hls~
class DashProvider~EngineType = Dash~

class MediaFileProvider~EngineType = HTMLMediaElement~ {
    #mediaEl?: HTMLMediaElement
    +src: string
    +readyState: ReadyState
    +networkState: NetworkState
    +crossOrigin?: true | anonymous | credentials
    +preload?: true | none | metadata | auto
    +poster?: string
    +controlsList?: string
    +autoPiP?: string
    +disablePiP?: boolean
    +disableRemotePlayback?: boolean
}

MediaFileProvider <|-- AudioProvider: extends
MediaFileProvider <|-- VideoProvider: extends
VideoProvider <|-- HlsProvider: extends
VideoProvider <|-- DashProvider: extends

class MediaProvider~EngineType~ {
    <<abstract>>
    +currentTime: number
    +volume: number
    +controls: boolean
    +playsinline: boolean
    +mediaType: MediaType
    +viewType: ViewType
    ...

    play()* Promise~void~
    pause()* Promise~void~
    canPlay(type: string)* CanPlayType
    engine()* EngineType
    requestFullscreen()* Promise~void~
    exitFullscreen()* Promise~void~
}

MediaProvider <|-- MediaFileProvider
MediaProvider <|-- MediaEmbedProvider