import type { MediaState } from './store';

export const MEDIA_ATTRIBUTES: (keyof MediaState)[] = [
  'autoplay',
  'autoplayError',
  'canFullscreen',
  'canPictureInPicture',
  'canLoad',
  'canPlay',
  'canSeek',
  'ended',
  'error',
  'fullscreen',
  'loop',
  'live',
  'liveEdge',
  'mediaType',
  'muted',
  'paused',
  'pictureInPicture',
  'playing',
  'playsinline',
  'seeking',
  'started',
  'streamType',
  'userIdle',
  'viewType',
  'waiting',
];
